// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6647.Voltres.subsystems;

import org.usfirst.frc6647.Voltres.RobotMap;


import org.usfirst.frc6647.Voltres.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;

import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import com.ctre.phoenix.motorcontrol.ControlMode;


public class Lift extends Subsystem {

    private static int direction1 = 1;
    private static int direction2 = -1;
    private static double lift_up_speed = 0.7;
    private static double lift_down_speed = 0.7;
    private static WPI_VictorSPX liftMain;

    public Lift() {
        liftMain = RobotMap.liftMain;
    }

    @Override
    public void initDefaultCommand() {
        Stop_Lift();
    }

    public void Lift_Up(){
        liftMain.set(ControlMode.PercentOutput, lift_up_speed*direction1);
    }

    public void Lift_Down(){
        liftMain.set(ControlMode.PercentOutput, lift_down_speed*direction2);
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

   public void Stop_Lift(){
    liftMain.set(ControlMode.PercentOutput, 0.0);
   }
}

