// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6647.Voltres.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6647.Voltres.Robot;
import org.usfirst.frc6647.Voltres.RobotMap;

/**
 *
 */
public class HAB3 extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public HAB3() {
        requires(Robot.robotDrive);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        setTimeout(.35);
        Robot.robotDrive.HABFront_Up();
        Robot.robotDrive.HABBack_Up();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if (isTimedOut()){
            if (RobotMap.NAVX.getPitch()>5){
                Robot.robotDrive.HABFront_Stop();
                setTimeout(.35);

            }else if (RobotMap.NAVX.getPitch()<-5){
                Robot.robotDrive.HABBack_Stop();
                setTimeout(.35);

            }else {
                Robot.robotDrive.HABFront_Up();
                Robot.robotDrive.HABBack_Up();
                setTimeout(.35);

            }

        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.robotDrive.HABFront_Stop();
        Robot.robotDrive.HABBack_Stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
